import { TrunkNode, BranchNode, ShadowTimeline, MutationEvent, CanonWar, RisingShadowBranch } from "./types";

export const TRUNK_NODES: TrunkNode[] = [
  { id: "t1", label: "The First Ember", type: "origin", depth: 0, summary: "The world-seed event. Fire born from the dying god Ashur." },
  { id: "t2", label: "Rise of the Ashfall Kingdoms", type: "chapter", depth: 1, summary: "Four kingdoms form in the aftermath of the Cinder Wars." },
  { id: "t3", label: "The Iron Compact", type: "lore", depth: 2, summary: "A political treaty signed in ash and blood." },
  { id: "t4", label: "Age of Embers", type: "chapter", depth: 3, summary: "A century of fragile peace before the Second Burning." },
  { id: "t5", label: "The Second Burning", type: "event", depth: 4, summary: "Volcanic catastrophe reshapes the continent." },
  { id: "t6", label: "Solvara's Ascent", type: "canon", depth: 5, summary: "The Last Ember Queen rises from the ruins." },
];

export const BRANCHES: BranchNode[] = [
  { id: "b1", label: "The Forgotten Vaults", trunkNodeId: "t2", strength: "major", nodes: 18, contributors: 12, forks: 3, summary: "What lies buried beneath the oldest kingdom?" },
  { id: "b2", label: "Ashur's Remnants", trunkNodeId: "t3", strength: "major", nodes: 31, contributors: 24, forks: 7, summary: "A cult that worships the original dying god." },
  { id: "b3", label: "The Cold Compact", trunkNodeId: "t3", strength: "minor", nodes: 4, contributors: 2, forks: 1, summary: "An alternate treaty that never existed in canon." },
  { id: "b4", label: "Ember Wars Retold", trunkNodeId: "t4", strength: "thriving", nodes: 67, contributors: 41, forks: 19, summary: "The full history from the soldiers' perspective." },
  { id: "b5", label: "The Ninth Kingdom", trunkNodeId: "t5", strength: "minor", nodes: 7, contributors: 3, forks: 2, summary: "A secret kingdom hidden in volcanic tunnels." },
  { id: "b6", label: "Solvara's Shadow", trunkNodeId: "t6", strength: "major", nodes: 22, contributors: 15, forks: 8, summary: "What the Ember Queen sacrificed to rise." },
  { id: "b7", label: "The Glass Prophets", trunkNodeId: "t1", strength: "fading", nodes: 2, contributors: 1, forks: 0, summary: "Seers who foresaw the First Ember." },
];

export const SHADOW_BRANCHES: BranchNode[] = [
  { id: "s1", label: "Ashur Never Died", trunkNodeId: "t1", strength: "thriving", nodes: 89, contributors: 52, forks: 34, summary: "What if the god survived and walks among mortals?" },
  { id: "s2", label: "The Fifth Kingdom", trunkNodeId: "t2", strength: "major", nodes: 34, contributors: 18, forks: 11, summary: "A kingdom erased from history, now remembered." },
  { id: "s3", label: "Cinder Punk", trunkNodeId: "t5", strength: "thriving", nodes: 113, contributors: 77, forks: 45, summary: "Industrial revolution in a volcanic wasteland. Steam and ash." },
  { id: "s4", label: "No Compact, Ever", trunkNodeId: "t3", strength: "fading", nodes: 3, contributors: 1, forks: 0, summary: "A timeline where no peace was ever made." },
  { id: "s5", label: "The Ember Queen's Daughter", trunkNodeId: "t6", strength: "major", nodes: 28, contributors: 14, forks: 9, summary: "An heir who never existed in canon." },
  { id: "s6", label: "The Second God", trunkNodeId: "t1", strength: "major", nodes: 41, contributors: 22, forks: 13, summary: "Another deity hidden in the cinders of creation." },
  { id: "s7", label: "Ash Democracy", trunkNodeId: "t2", strength: "minor", nodes: 9, contributors: 5, forks: 2, summary: "What if the kingdoms voted instead of warred?" },
  { id: "s8", label: "The Reverse Burning", trunkNodeId: "t5", strength: "minor", nodes: 6, contributors: 3, forks: 1, summary: "Catastrophe reversed — volcanic winter instead." },
  { id: "s9", label: "Solvara the Betrayer", trunkNodeId: "t6", strength: "thriving", nodes: 78, contributors: 44, forks: 28, summary: "In this telling, she burns the world herself." },
  { id: "s10", label: "The Nameless Wars", trunkNodeId: "t4", strength: "major", nodes: 33, contributors: 19, forks: 7, summary: "Wars fought before history was written." },
];

export const RISING_SHADOW_BRANCHES: RisingShadowBranch[] = [
  {
    id: "r1",
    label: "Cinder Punk",
    trunkNodeId: "t5",
    nodes: 113,
    contributors: 77,
    growth: "+23 nodes this week",
    summary: "Industrial revolution in a volcanic wasteland. The fastest-growing branch in the Shadow.",
    tags: ["alternate history", "industrial", "community favorite"],
  },
  {
    id: "r2",
    label: "Solvara the Betrayer",
    trunkNodeId: "t6",
    nodes: 78,
    contributors: 44,
    growth: "+18 nodes this week",
    summary: "A radical re-reading of Solvara as the true villain of Ashfall.",
    tags: ["villain arc", "controversial", "hot"],
  },
  {
    id: "r3",
    label: "Ashur Never Died",
    trunkNodeId: "t1",
    nodes: 89,
    contributors: 52,
    growth: "+14 nodes this week",
    summary: "The original god walks among mortals. The oldest running shadow branch.",
    tags: ["mythology", "godhood", "long-running"],
  },
  {
    id: "r4",
    label: "The Ember Queen's Daughter",
    trunkNodeId: "t6",
    nodes: 28,
    contributors: 14,
    growth: "+9 nodes this week",
    summary: "A secret heir. A throne. An impossible inheritance.",
    tags: ["lineage", "new", "rising"],
  },
];

export const SHADOW_TIMELINES: ShadowTimeline[] = [
  {
    id: "st1",
    label: "The Ashur Walks Timeline",
    originBranch: "Ashur Never Died",
    nodes: 89,
    contributors: 52,
    velocity: "explosive",
    summary: "Ashur alive changes everything. This timeline spirals outward faster than any canon structure could contain.",
    lastActivity: "4 min ago",
  },
  {
    id: "st2",
    label: "Cinder Age Progression",
    originBranch: "Cinder Punk",
    nodes: 113,
    contributors: 77,
    velocity: "fast",
    summary: "An industrial revolution narrative that has grown its own sub-timelines. Four forks of the Cinder Age now exist.",
    lastActivity: "11 min ago",
  },
  {
    id: "st3",
    label: "The Betrayer's Court",
    originBranch: "Solvara the Betrayer",
    nodes: 41,
    contributors: 22,
    velocity: "fast",
    summary: "Solvara's alternate court politics. Two contributor factions disagree on whether she acts alone.",
    lastActivity: "32 min ago",
  },
  {
    id: "st4",
    label: "Fifth Kingdom Genealogies",
    originBranch: "The Fifth Kingdom",
    nodes: 17,
    contributors: 9,
    velocity: "steady",
    summary: "Deep lore on the erased bloodlines. Slow, meticulous, obsessive.",
    lastActivity: "2h ago",
  },
  {
    id: "st5",
    label: "The Nameless Campaigns",
    originBranch: "The Nameless Wars",
    nodes: 28,
    contributors: 14,
    velocity: "steady",
    summary: "Military history for wars without names. Tactical, grim, procedurally expanding.",
    lastActivity: "3h ago",
  },
  {
    id: "st6",
    label: "No Peace Timeline",
    originBranch: "No Compact, Ever",
    nodes: 3,
    contributors: 1,
    velocity: "decaying",
    summary: "Started strong. Now nearly abandoned. The darkness of a world that never stopped burning.",
    lastActivity: "6d ago",
  },
];

export const MUTATION_EVENTS: MutationEvent[] = [
  {
    id: "m1",
    original: "The Iron Compact",
    mutation: "The Molten Compact",
    branch: "Cinder Punk",
    mutatedBy: "Tev Ashhar",
    forkCount: 12,
    summary: "The original treaty rewritten in a world of steam and industry. Legal language mutated into worker contracts.",
    time: "1h ago",
  },
  {
    id: "m2",
    original: "Solvara's Ascent",
    mutation: "Solvara's Descent",
    branch: "Solvara the Betrayer",
    mutatedBy: "Nara Vel",
    forkCount: 28,
    summary: "The ascent node inverted. Every detail of canon reread as a fall, not a rise.",
    time: "3h ago",
  },
  {
    id: "m3",
    original: "The First Ember",
    mutation: "The First Drowning",
    branch: "Ashur Never Died",
    mutatedBy: "Rook Seld",
    forkCount: 7,
    summary: "What if the origin event was water, not fire? An elemental re-reading of the creation myth.",
    time: "8h ago",
  },
  {
    id: "m4",
    original: "Age of Embers",
    mutation: "Age of Machines",
    branch: "Cinder Punk",
    mutatedBy: "Y. Maren",
    forkCount: 19,
    summary: "The century of fragile peace becomes a century of rapid industrialization. Steam replaces flame.",
    time: "1d ago",
  },
];

export const CANON_WARS: CanonWar[] = [
  {
    id: "cw1",
    title: "Did Solvara betray the Compact?",
    sideA: "She upheld it — her ascent was earned",
    sideB: "She destroyed it — the burning was her doing",
    nodeCountA: 31,
    nodeCountB: 44,
    summary: "The longest-running contested narrative in the Ashfall Shadow. Over 200 contributors have weighed in.",
    status: "escalating",
  },
  {
    id: "cw2",
    title: "Is the Fifth Kingdom a memory or a lie?",
    sideA: "It existed and was erased by the victors",
    sideB: "It is collective mythology, never real",
    nodeCountA: 22,
    nodeCountB: 15,
    summary: "Competing schools of in-universe historiography clash across dozens of nodes.",
    status: "active",
  },
  {
    id: "cw3",
    title: "Ashur: dead god or sleeping god?",
    sideA: "Ashur died to create the world",
    sideB: "Ashur sleeps beneath the volcanoes",
    nodeCountA: 18,
    nodeCountB: 67,
    summary: "The Shadow almost unanimously sides with the sleeping god theory. Canon stands alone.",
    status: "active",
  },
];
